# A function which takes in a plain text file and removes the timestamps generated by OpenAI's Whisper.

# The function is useful because Whisper outputs timestamps at every utterance, which potentially clutters transcripts.


import argparse
import os

def read_vtt_file(filename):
    if not os.path.isfile(filename):
        print('File does not exist.')
        return

    lines_without_timestamps = []
    with open(filename, 'r') as file:
        lines = file.readlines()
        for line in lines:
            if '-->' not in line and line.strip():
                lines_without_timestamps.append(line)

        new_filename = filename.replace('.vtt', '_postprocess.vtt')
        with open(new_filename, 'w') as file:
            file.writelines(lines_without_timestamps)


def main():
    parser = argparse.ArgumentParser(description='Remove timestamps from .vtt files.')

    parser.add_argument('--files', metavar='-F', type=str, nargs='+',
                        help='one or more .vtt files to be processed')

    args = parser.parse_args()

    for filename in args.files:
        if filename.endswith('.vtt') or filename.endswith('.txt'):
            read_vtt_file(filename)
        else:
            print('Invalid file: ' + filename + ' (file must end with .vtt or .txt)')

if __name__ == "__main__":
    main()